### PR TITLE
Add model utils

### PR DESCRIPTION
**Pull request by picturesbyrobots**
model utilities ported over from hmltdev.

### CODE REVIEW

**Comment by s4y** [comment]
I’m trying to keep this fork as a mirror of s4y/space except in special and temporary cases where we need to fix something for the show. Mind submitting this to https://github.com/theweeklyweekly/homewardbound, instead?

**Comment by picturesbyrobots** [comment]
I see. So if I would like to be able to import these modules into a custom type I've created where would you suggest I put them? In the same directory as the type?

**Comment by s4y** [comment]
How about something like `/static/util/`?

**Comment by picturesbyrobots** [comment]
ok will do!

**Pull request closed without merging**
